server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HypeBoys?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hong3622!

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

app:
    SECRET_KEY: NewJeansHaerin
    client_id: af1bb52400164cf8aa4258e5dcfd7acabb481399210d48bb8c4e8e85226f4c78
    client_secret: 53972e6ce26943e4a8f3ade2a8bd07f8bcd845553bfe4fc3a957e97e34cb6d43
    auth_url: http://dauth.b1nd.com/api
    open_api_url: http://open.dodam.b1nd.com/api